### ISSUE TITLE
Transformer version issue

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/claf#2]
```
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from claf.config import args
  File "/home/yyoo/src/claf/claf/__init__.py", line 4, in <module>
    from claf.data.reader import *
  File "/home/yyoo/src/claf/claf/data/reader/__init__.py", line 2, in <module>
    from claf.data.reader.seq_cls import SeqClsReader
  File "/home/yyoo/src/claf/claf/data/reader/seq_cls.py", line 9, in <module>
    from claf.data.dataset.seq_cls import SeqClsDataset
  File "/home/yyoo/src/claf/claf/data/dataset/__init__.py", line 6, in <module>
    from claf.data.dataset.bert.multi_task import MultiTaskBertDataset
  File "/home/yyoo/src/claf/claf/data/dataset/bert/multi_task.py", line 7, in <module>
    from claf.factory.data_loader import make_data_loader
  File "/home/yyoo/src/claf/claf/factory/__init__.py", line 4, in <module>
    from claf.factory.model import ModelFactory
  File "/home/yyoo/src/claf/claf/factory/model.py", line 7, in <module>
    from claf.tokens import token_embedder
  File "/home/yyoo/src/claf/claf/tokens/__init__.py", line 6, in <module>
    from claf.tokens.tokenizer import PassText
  File "/home/yyoo/src/claf/claf/tokens/tokenizer/__init__.py", line 6, in <module>
    from .subword import SubwordTokenizer
  File "/home/yyoo/src/claf/claf/tokens/tokenizer/subword.py", line 3, in <module>
    from transformers.tokenization_bert import load_vocab
ModuleNotFoundError: No module named 'transformers.tokenization_bert'
```

**Comment by ys7yoo** [comment]
downgrade `transformers`
https://github.com/NVIDIA/NeMo/issues/1566

**Comment by ys7yoo** [comment]
Does 3.5 work?
```
pip uninstall transformers
pip install transformers==3.5
```

**Comment by ys7yoo** [comment]
Downgrade to 2.11.0 ?
```
pip uninstall transformers
pip install transformers==2.11.0
```
