### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/claf#7]
```
python train.py --base_config korquad/bert_base_multilingual_uncased
```

```
2021-04-24 16:30:42,819 (modeling_utils.py:650): [INFO] - loading weights file https://cdn.huggingface.co/bert-base-multilingual-uncased-pytorch_model.bin from cache at /home/yyoo/.claf_cache/b72dd13aa8437628227c4928499f2476a84af4ab7ed75eb1365c5ae9fdbd7638.54b4dad9cc3db9aa8448458b782d11ab07c80dedb951906fd2f684a00ecdb1ee
2021-04-24 16:30:48,149 (modeling_utils.py:741): [INFO] - Weights of BertForQuestionAnswering not initialized from pretrained model: ['qa_outputs.weight', 'qa_outputs.bias']
2021-04-24 16:30:48,149 (modeling_utils.py:747): [INFO] - Weights from pretrained model not used in BertForQuestionAnswering: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
2021-04-24 16:30:50,799 (experiment.py:327): [INFO] - use_gpu: True num_gpu: 1, distributed training: False, 16-bits training: False
2021-04-24 16:30:50,866 (trainer.py:356): [INFO] - # Train Mode.
2021-04-24 16:30:51,058 (trainer.py:389): [INFO] -   Start - Batch Loss: 6.31731
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    experiment()
  File "/home/yyoo/src/claf/claf/learn/experiment.py", line 142, in __call__
    self.trainer.train_and_evaluate(train_loader, valid_loader, optimizer)
  File "/home/yyoo/src/claf/claf/learn/trainer.py", line 137, in train_and_evaluate
    eval_and_save_step_count=self.eval_and_save_step_count,
  File "/home/yyoo/src/claf/claf/learn/trainer.py", line 376, in _run_epoch
    output_dict = self.model(**inputs)
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyoo/src/claf/claf/model/reading_comprehension/bert.py", line 72, in forward
    bert_inputs, token_type_ids=token_type_ids, attention_mask=attention_mask
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyoo/torch/lib/python3.6/site-packages/transformers/modeling_bert.py", line 1450, in forward
    inputs_embeds=inputs_embeds,
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyoo/torch/lib/python3.6/site-packages/transformers/modeling_bert.py", line 734, in forward
    encoder_attention_mask=encoder_extended_attention_mask,
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyoo/torch/lib/python3.6/site-packages/transformers/modeling_bert.py", line 408, in forward
    hidden_states, attention_mask, head_mask[i], encoder_hidden_states, encoder_attention_mask
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyoo/torch/lib/python3.6/site-packages/transformers/modeling_bert.py", line 369, in forward
    self_attention_outputs = self.attention(hidden_states, attention_mask, head_mask)
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyoo/torch/lib/python3.6/site-packages/transformers/modeling_bert.py", line 315, in forward
    hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyoo/torch/lib/python3.6/site-packages/transformers/modeling_bert.py", line 236, in forward
    attention_scores = attention_scores / math.sqrt(self.attention_head_size)
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 11.78 GiB total capacity; 10.23 GiB already allocated; 49.88 MiB free; 10.33 GiB reserved in total by PyTorch)
```

**Comment by ys7yoo** [comment]
Use multiple GPUs?
```
2021-04-24 16:36:52,816 (modeling_utils.py:650): [INFO] - loading weights file https://cdn.huggingface.co/bert-base-multilingual-uncased-pytorch_model.bin from cache at /home/yyoo/.claf_cache/b72dd13aa8437628227c4928499f2476a84af4ab7ed75eb1365c5ae9fdbd7638.54b4dad9cc3db9aa8448458b782d11ab07c80dedb951906fd2f684a00ecdb1ee
2021-04-24 16:36:57,130 (modeling_utils.py:741): [INFO] - Weights of BertForQuestionAnswering not initialized from pretrained model: ['qa_outputs.weight', 'qa_outputs.bias']
2021-04-24 16:36:57,130 (modeling_utils.py:747): [INFO] - Weights from pretrained model not used in BertForQuestionAnswering: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    experiment()
  File "/home/yyoo/src/claf/claf/learn/experiment.py", line 134, in __call__
    train_loader, valid_loader, optimizer = self.set_train_mode()
  File "/home/yyoo/src/claf/claf/learn/experiment.py", line 220, in set_train_mode
    model = self._create_model(token_makers, helpers=helpers)
  File "/home/yyoo/src/claf/claf/learn/experiment.py", line 307, in _create_model
    model = self._set_gpu_env(model)
  File "/home/yyoo/src/claf/claf/learn/experiment.py", line 317, in _set_gpu_env
    model = torch.nn.DataParallel(model, device_ids=cuda_devices)
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/_utils.py", line 459, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/_utils.py", line 459, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/_utils.py", line 442, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/_utils.py", line 459, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/yyoo/torch/lib/python3.6/site-packages/torch/cuda/__init__.py", line 309, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```
